apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple_server.fullname" . }}-nodeport
  labels:
    {{- include "simple_server.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 32761
      protocol: TCP
  selector:
    {{- include "simple_server.selectorLabels" . | nindent 4 }}
